CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

INSERT INTO users (username, password_hash, created_at, updated_at)
VALUES (
    'legacy_user',
    '$2a$10$J0h1FzEiK8QGmfKc3WMFyuHh7zE8Mu4k6MFcaJFKw1SeUWaIeG8ra',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

ALTER TABLE todos
    ADD COLUMN user_id BIGINT;

UPDATE todos
SET user_id = (SELECT id FROM users WHERE username = 'legacy_user')
WHERE user_id IS NULL;

ALTER TABLE todos
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE todos
    ADD CONSTRAINT fk_todos_user
    FOREIGN KEY (user_id) REFERENCES users(id);
