CREATE TABLE todo_action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_todo_action_logs_todo FOREIGN KEY (todo_id) REFERENCES todos(id),
    CONSTRAINT fk_todo_action_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_todo_action_logs_todo_id_created_at
    ON todo_action_logs (todo_id, created_at);

CREATE INDEX idx_todo_action_logs_user_id
    ON todo_action_logs (user_id);
