CREATE TABLE todo_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_todo_attachments_todo FOREIGN KEY (todo_id) REFERENCES todos(id),
    CONSTRAINT fk_todo_attachments_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_todo_attachments_todo_id_created_at
    ON todo_attachments (todo_id, created_at);

CREATE INDEX idx_todo_attachments_user_id
    ON todo_attachments (user_id);
